### ISSUE TITLE
Separate force:true parameter from api call to update rules by tag

### ISSUE THREAD

**Issue by Cjames21082** [fastly/waflyctl#63]
# Separate force:true parameter from api call to update rules by tag

## Overview

1. Chrome, Version 70.0.3538.77
2. `go version` go version go1.11.1 darwin/amd64
3. `waflyctl --version` 0.2.1
4. Description of the problem. What is happening that shouldn't?

Use case: User has rules associated with the tag=OWASP in both log and disabled status. Should the user use waflyctl to switch the tag to block mode, all rules are reset to block mode (including disabled). This is not the intent of a user.  

5. Description of the expected behaviour.

There is a force:true parameter in the API call that should *optional*. 

The customer will want to do: 
- switch rules by tags between block/log with disabled rules not affected.

A separate flag should exist that allows customers to decide to reset disabled rules with the `force:true parameter`

6. Exact steps to reproduce the use case.

a. disable some rules within owasp
b. check status overview: 

```
# View WAF Summary
curl -s -H "Fastly-Key:$token" "https://api.fastly.com/service/$service_id/version/$version/wafs?include=configuration_set" | jq '.data[]'
```

c. Command: 
```
waflyctl --apikey $token --serviceid $sid --action block --tags OWASP --config XXX.toml
```

Code: 
```
//set rule action on our tags
		apiCall := apiEndpoint + "/service/" + serviceID + "/wafs/" + wafID + "/rule_statuses"

		resp, err = resty.R().
			SetHeader("Accept", "application/vnd.api+json").
			SetHeader("Fastly-Key", apiKey).
			SetHeader("Content-Type", "application/vnd.api+json").
			SetBody(`{"data": {"attributes": {"status": "` + config.Action + `","name": "` + tag + `","force": true},"id": "` + wafID + `","type": "rule_status"}}`).
			Post(apiCall)
```
d. Check waf summary again

All rules are tagged with OWASP are in block mode

**Comment by ejthurgo** [comment]
Do we think the `force` parameter also needs to be part of the config file?
Doing so introduces the following issue:
Specifying `--force-status` boolean flag is ambiguous in that we don't know whether the intent is to override what's in the config with `false`, or whether we should not override config at all (which may be set to `true`). We would need to express this parameter like `--force-status=true|false` to be more explicit.
However, if it's unlikely that this will need to be done via config file, it can just be a CLI parameter, the presence/absence of which will signify true/false. This is my preference, but I've less experience with the use-case; so advice would be helpful.

**Comment by Cjames21082** [comment]
> Do we think the `force` parameter also needs to be part of the config file?
No. When a new ruleset is created, the initial action will be set for all rules by tag name. 

> Specifying `--force-status` boolean flag is ambiguous in that we don't know whether the intent is to override what's in the config with `false`, or whether we should not override config at all (which may be set to `true`). We would need to express this parameter like `--force-status=true|false` to be more explicit.

If we were to consider expressing the parameter like `--force-status=true|false`, the default should be false and with reference to the API call (do not include the force parameter). This can also allows for the absence of the flag (defaulting to false). The intent is generally to reset all rules by tag name to a specific action (log, block). This would be when the user wants to use the flag signifying `true`. I favor the option of a just be a CLI parameter. Absence = false, Presence = true.

**Comment by ejthurgo** [comment]
OK, I will not add this to the config file, this will be a CLI override only.
Should we be concerned about backwards compatibility here? We're essentially changing the default behaviour. I'd err on the side of "it's probably ok", but some sort of consensus is better.
