### ISSUE TITLE
Mistake in generated Filename for backup

### ISSUE THREAD

**Issue by LittleLadySunshine** [fastly/waflyctl#64]
# Mistake in generated Filename for Backup toml

## Overview

1. OS name and version.
>High Sierra - 10.13.6 
2. `go version` output
>N/A
3. `waflyctl --version` in recent releases or `brew info waflyctl` output.
>`waflyctl 0.2.1`
4. Description of the problem. What is happening that shouldn't?
>Filename gets printed as `waflyclt_serviceid.toml`
5. Description of the expected behaviour.
>Filename should be `waflyctl_serviceid.toml`
6. Exact steps to reproduce the error.
>Open terminal, run the following command: `waflyctl --apikey $FASTLY_TOKEN --serviceid 16hUfNKlIvNGIZ4Rkd5IG5 --backup --config ~/desktop/waflyctl.toml` 
 
>Look at the output of the filename ...simple letter jumble.

## Additional Information:

1. Logs showing errors or behaviour.
2. Steps which have been taken to try address the issue.
3. Other data which indicates what may be causing the issue.
4. Stack trace if any error is seen.

**Comment by ejthurgo** [comment]
It's the SID for me. Although I'm running build from master.
Are you sure it's the right file and not an old backup, the version I runs saves to the same path as the waflyctl executable, NOT the home directory as described in the --help.
However, there is a change incoming here, you'll soon be able to specify the filename for the backup (or it will default to the `waflyclt_[SERVICEID].toml`)

**Comment by LittleLadySunshine** [comment]
it's the clt that needs to change to waflyctl that needs to happen.

**Comment by ejthurgo** [comment]
ah! `clt`, `ctl`. Sorry I get what you mean now.

**Comment by ejthurgo** [comment]
Resolved by changes in https://github.com/fastly/waflyctl/pull/66
