### ISSUE TITLE
Cloned Service Configuration Not Activated w/o Any Message

### ISSUE THREAD

**Issue by minus27** [fastly/waflyctl#72]
# Cloned Service Configuration Not Activated w/o Any Message

## Overview

1. OS name and version.
N/A
2. `go version` output
N/A
3. `waflyctl --version` in recent releases or `brew info waflyctl` output.
>Fastly WAF Control Tool version: 0.2.1 built on 2018-11-09T16:21:56Z by #team-soc
4. Description of the problem. What is happening that shouldn't?
`waflyctl` clones the active configuration, does its magic, and then nothing.  It does not activate the draft configuration or notify the user to so, which used to be the case:
```
INFO: 2018/06/14 22:25:29 waflyctl.go:935: Config Version 3 Valid, remember to activate it!
```
5. Description of the expected behaviour.
At a minimum, there should be some sort of big and ugly, cannot be missed activation reminder message.
**Ideally, it would be great if there additionally was an `--activate` flag that would optionally instruct `waflyctl` to activate the draft configuration.**
6. Exact steps to reproduce the error.
Run `waflyctl` and no activation reminder message is logged.

## Additional Information:

1. Logs showing errors or behaviour.
N/A
2. Steps which have been taken to try address the issue.
N/A
3. Other data which indicates what may be causing the issue.
N/A
4. Stack trace if any error is seen.
N/A

**Comment by fgsch** [comment]
I've added the text back. 

Once we revamp the command handling we can consider having an --activate flag.
