### ISSUE TITLE
Backup missing out a page of rules

### ISSUE THREAD

**Issue by ejthurgo** [fastly/waflyctl#75]
# Issue Name

## Overview

1. OS name and version.
Any
2. `go version` output
Any
3. `waflyctl --version` in recent releases or `brew info waflyctl` output.
0.2.1
4. Description of the problem. What is happening that shouldn't?
When performing a backup, although the tool advertises that it has pulled the full set of rules (multiple API calls for paged data) the logic actually consistently loses data.
The first call for the head page does not specify a page size so is returned with 100 rules. Requests for the subsequent pages are hard coded for 200 rules. However, it starts at page 2, meaning rules 101-200 are consistently lost and not part of the backup.
5. Description of the expected behaviour.
It should not ignore data.
6. Exact steps to reproduce the error.
Do a backup where a service has more than 100 rules.

**Comment by ejthurgo** [comment]
Fix for this is coded already, pending PR

**Comment by fgsch** [comment]
Should be fixed by 6477f49f3b092fc882b6affdc238f093dd5581b7.
